BlogController_show:
    pattern:   /post/(?P<id>[1-9][0-9]*)
    connect:  Controllers\BlogController:show
    params: id
BlogController_index:
    pattern:   /
    connect:  Controllers\BlogController:index